FROM httpd:2.4
MAINTAINER Boris Jamot
COPY httpd.conf /usr/local/apache2/conf/httpd.conf
COPY apache-vhost.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf
COPY index.html /usr/local/apache2/htdocs/
